services:
  mariadb:
    image: mariadb:11.0
    container_name: doorbell_db
    restart: unless-stopped
    environment:
      TZ: Europe/Lisbon
      MARIADB_ROOT_PASSWORD: houseof5
      MARIADB_DATABASE: doorbell"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - doorbell-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: doorbell_backend
    restart: unless-stopped
    environment:
      TZ: Europe/Lisbon
      APP_SECRET_KEY: ${APP_SECRET_KEY}
      ONESIGNAL_APP_ID: ${ONESIGNAL_APP_ID}
      ONESIGNAL_API_KEY: ${ONESIGNAL_API_KEY}
      ROUTING_DESTINATION_LAT: ${ROUTING_DESTINATION_LAT}
      ROUTING_DESTINATION_LNG: ${ROUTING_DESTINATION_LNG}
    ports:
      - "2080:8080"
    depends_on:
      - mariadb
    networks:
      - doorbell-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: doorbell_frontend
    restart: unless-stopped
    environment:
      TZ: Europe/Lisbon
    ports:
      - "2081:3000"
    depends_on:
      - mariadb
    networks:
      - doorbell-network

  osrm:
    image: osrm/osrm-backend
    ports:
      - "5000:5000"
    volumes:
      - ./data/map:/data/map
    working_dir: /data/map
    command: >
      sh -c "
        if [ ! -f lisboa.osrm ]; then
          osrm-extract -p /opt/foot.lua lisboa.osm.pbf &&
          osrm-contract lisboa.osrm;
        fi &&
        osrm-routed --algorithm ch lisboa.osrm
      "
    networks:
      - doorbell-network

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./certs:/mosquitto/certs:ro
      - ./passwords:/mosquitto/passwords:ro

volumes:
  mariadb_data:

networks:
  doorbell-network:
    driver: bridge
