export const API_BASE_URL = 'https://doorbell-backend.houseofknowledge.pt';
export const API_TIMEOUT = 10000;

export const API_ENDPOINTS = {
  LOGIN: '/auth/login',
  REGISTER: '/auth/register', 
  LOGOUT: '/auth/logout', 
  USER_ME: '/users/me',
  USERS: '/users/',
  DOOR: '/door',
  DOOR_PING: '/door/ping',
  DOOR_ENVIRONMENT: '/door/environment',
  DOOR_ONLINE: '/door/online',
  PARTIES: '/party/',
  CREATE_PARTY: '/party',
  DELETE_PARTY: '/party',
  UPDATE_GUEST_STATUS: '/party/',
  NOTIFICATIONS_UNREAD: '/notifications/unread',
  NOTIFICATIONS_ALL: '/notifications',
  NOTIFICATIONS_MARK_READ: '/notifications',
  NOTIFICATIONS_HAS_UNREAD: '/notifications/has-unread',
  MAINTENANCE_STATUS: '/maintenance/status',
  MAINTENANCE_ACTIVATE: '/maintenance/activate',
  MAINTENANCE_DEACTIVATE: '/maintenance/deactivate',
  REGISTRATION_STATUS: '/maintenance/registration-status',
  BLOCK_REGISTRATION: '/maintenance/block-registration',
  UNBLOCK_REGISTRATION: '/maintenance/unblock-registration',
  FORGOT_PASSWORD: '/auth/forgot-password',
  FORGOT_PASSWORD_STATUS: '/auth/forgot-password/status',
  RESET_PASSWORD: '/auth/reset-password',
  PASSWORD_RESET_REQUESTS: '/maintenance/password-reset-requests',
  APPROVE_PASSWORD_RESET: '/maintenance/password-reset-requests',
  REJECT_PASSWORD_RESET: '/maintenance/password-reset-requests',
  LOGS_PAGINATED: '/logs/paginated',
  LOGS_COUNT: '/logs/count',
};
